importScripts('https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js');

if(workbox)
{
	console.log('Workbox Loaded!');
}
else
{
	console.log('workbox failed to load? wtf');
}

const urlsToCache = [
	{ url: "/", revision: '1' },
	{ url: "/nav.html", revision: '1' },
	{ url: "/index.html", revision: '1' },
	{ url: "/gt_jumbo.html", revision: '1' },
	{ url: "/gt_kecil_lengkung.html", revision: '1' },
	{ url: "/gt_kecil_lurus.html", revision: '1' },
	{ url: "/gt_khusus.html", revision: '1' },
	{ url: "/gt_sedang_lengkung.html", revision: '1' },
	{ url: "/gt_sedang_lurus.html", revision: '1' },
	{ url: "/manifest.json", revision: '1' },
	{ url: "/service-worker.js", revision: '1' },
	{ url: "/assets/css/materialize.min.css", revision: '1' },
	{ url: "/assets/css/style-custom.css", revision: '1' },
	{ url: "/assets/css/style-galery.css", revision: '1' },
	{ url: "/assets/js/materialize.min.js", revision: '1' },
	{ url: "/assets/js/nav.js", revision: '1' },
	{ url: "/assets/js/jquery-migrate-3.3.0.min.js", revision: '1' },
	{ url: "/assets/js/jquery-3.5.1.min.js", revision: '1' },
	{ url: "/assets/js/href.js", revision: '1' },
	{ url: "/assets/js/slick/slick.min.js", revision: '1' },
	{ url: "/assets/js/slick/slick.css", revision: '1' },
	{ url: "/assets/js/slick/slick-theme.css", revision: '1' },
	{ url: "/assets/js/slick/ajax-loader.gif", revision: '1' },
	{ url: "/assets/js/slick/fonts/slick.woff", revision: '1' },
	{ url: "https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js", revision: '1' },
	{ url: "https://kit.fontawesome.com/fd0c5ab4fe.js", revision: '1' },
	{ url: "https://kit-free.fontawesome.com/releases/latest/js/free-v4-shims.min.js", revision: '1' },
	{ url: "https://kit-free.fontawesome.com/releases/latest/js/free.min.js", revision: '1' },
	{ url: "/assets/images/apple-icon192x192.png", revision: '1' },
	{ url: "/assets/images/custom_trolly.png", revision: '1' },
	{ url: "/assets/images/handphone-transparan.png", revision: '1' },
	{ url: "/assets/images/icon192x192.png", revision: '1' },
	{ url: "/assets/images/icon24x24.png", revision: '1' },
	{ url: "/assets/images/icon512x512.png", revision: '1' },
	{ url: "/assets/images/landing-image1.png", revision: '1' },
	{ url: "/assets/images/landing-image2.png", revision: '1' },
	{ url: "/assets/images/landing-image3.png", revision: '1' },
	{ url: "/assets/images/logo-olx-white.png", revision: '1' },
	{ url: "/assets/images/logo-shopee-white.png", revision: '1' },
	{ url: "/assets/images/logo-tokopedia-white.png", revision: '1' },
	{ url: "/assets/images/new-logo.png", revision: '1' },
	{ url: "/assets/images/sms.svg", revision: '1' },
	{ url: "/assets/images/telephone.svg", revision: '1' },
	{ url: "/assets/images/troli_350F.png", revision: '1' },
	{ url: "/assets/images/troli_350F_lurus.png", revision: '1' },
	{ url: "/assets/images/troli_395F.png", revision: '1' },
	{ url: "/assets/images/troli_395F_lurus.png", revision: '1' },
	{ url: "/assets/images/troli_850.png", revision: '1' },
	{ url: "/assets/images/whatsapp.svg", revision: '1' },
	{ url: "/assets/images/troli_pic/custom1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/custom2.png", revision: '1' },
	{ url: "/assets/images/troli_pic/custom3.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/img1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/img2.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/img3.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/img4.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/img5.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_j1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_j2.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_j3.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_j4.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_j5.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_lengs1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_lengs2.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_lengs3.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_lengs4.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_lengs5.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_luruss1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_luruss2.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_luruss3.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_luruss4.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/gt_luruss5.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lengkung-1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lengkung-2.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lengkung-3.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lengkung-4.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lengkung-5.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lurus-1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lurus-2.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lurus-3.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lurus-4.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/pic-t-small-lurus-5.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/troli_khusus1.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/troli_khusus2.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/troli_khusus3.png", revision: '1' },
	{ url: "/assets/images/troli_pic/troli_khusus4.jpg", revision: '1' },
	{ url: "/assets/images/troli_pic/troli_khusus5.jpg", revision: '1' },
	{ url: "/assets/images/testipic/1.jpg", revision: '1' },
	{ url: "/assets/images/testipic/2.jpg", revision: '1' },
	{ url: "/assets/images/testipic/3.jpg", revision: '1' },
	{ url: "/assets/images/testipic/4.jpg", revision: '1' },
	{ url: "/assets/images/testipic/5.jpg", revision: '1' },
	{ url: "/pages/aboutus.html", revision: '1' },
	{ url: "/pages/contact.html", revision: '1' },
	{ url: "/pages/home.html", revision: '1' },
	{ url: "/pages/product.html", revision: '1' },
];

workbox.precaching.precacheAndRoute(urlsToCache);

workbox.routing.registerRoute(
	({request}) => request.destination === 'pages',
	new workbox.strategies.StaleWhileRevalidate()
);

/*
const CACHE_NAME = "cache-akuradz-web-v1";
var urlsToCache = [
	"/",
	"/nav.html",
	"/index.html",
	"/manifest.json",
	"/pages/home.html",
	"/pages/aboutus.html",
	"/pages/contact.html",
	"/pages/product.html",
	"assets/css/materialize.min.css",
	"assets/css/style-custom.css",
	"assets/js/materialize.min.js",
	"assets/images/landing-image.png",
	"assets/images/icon24x24.png",
	"assets/images/icon192x192.png",	
	"assets/images/icon512x512.png",
	"assets/images/apple-icon192x192.png",
	"assets/js/nav.js",
	"assets/js/href.js",
	"https://fonts.googleapis.com/icon?family=Material+Icons",
	"https://fonts.gstatic.com/s/materialicons/v52/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2"
];*/